version: "3"

services:
  nfl-rushing-backend-service:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_COMPONENT=${APP_COMPONENT}
      - DB_MAX_POOL_SIZE=2
      - DB_MIN_POOL_SIZE=1
      - DB_NAME=rushing_dev
      - DB_SSL=prefer
      - CONNECTION_RETRIES=5
      - READ_DB_HOST=postgres
      - READ_DB_PASS=password
      - READ_DB_PORT=5432
      - READ_DB_USER=postgres
      - WRITE_DB_HOST=postgres
      - WRITE_DB_PASS=password
      - WRITE_DB_PORT=5432
      - WRITE_DB_USER=postgres
    env_file:
      - .env
    volumes:
      - ./mount:/srv/root
    ports:
      - 5000:5000
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: password
    command: -c ssl=on -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.3/24
